- bin/sail
Simple fix for command location. I assume it's a typo.
> Fix command location typo

- bin/sail
The `sail` command is listening to `MYSQL_PORT` but Sail uses `DB_PORT`.
`docker-compose` reads env vars from `.env` files (by coincidence), so `DB_PORT` mostly works based on settings in `.env`.
However, in `docker-compose`, env vars set as system env vars over-ride that (much like how DotEnv works)
So, if you want to over-write certain setting, the `sail` command allows that:
```bash
export APP_PORT=${APP_PORT:-80}
export APP_SERVICE=${APP_SERVICE:-"laravel.test"}
export MYSQL_PORT=${MYSQL_PORT:-3306}
export WWWUSER=${WWWUSER:-$UID}
export WWWGROUP=${WWWGROUP:-$(id -g)}
```
That exports env vars for `docker-compose` to use, using either the value of the env var if already set, or defaulting to a sane value.
So you can do things like:
```bash
APP_PORT=8888 sail up -d
```
So, `sail` uses …
> Use `DB_PORT` instead of `MYSQL_PORT` in `sail` bin

- runtimes/7.4/Dockerfile
- runtimes/8.0/Dockerfile
gnupg will check the permissions of keys directory. 
if the permission not `600`, it will show a warning like `WARNING: unsafe permissions on homedir`
https://lists.gnupg.org/pipermail/gnupg-users/2003-October/020342.html
> fix: fix warning of gnupg

- runtimes/7.4/Dockerfile
- runtimes/8.0/Dockerfile
`sail artisan schema:dump` is not working on a fresh Laravel project using Sail. That's because the `mysqldump` command is not found. This can be fixed with this PR, that's installing `mysql-client`. However, I am not sure if `mysql-client` was left out on purpose so I won't expect this to be merged. I know I can do this myself by exposing the Docker folder but I was just curious to read other opinions.
- Install fresh project with sail
- run `sail artisan schema:dump`
- verify error about `mysqldump`
- Install fork
- `sail build --no-cache`
- `sail up`
- run `sail artisan schema:dump` and verify it's working as expected
> Fix artisan schema:dump command in Sail environment 

- runtimes/7.4/Dockerfile
- runtimes/8.0/Dockerfile
This fixes two dependency issues which cause errors when running the command in Nova to create a new tool, eg:
`sail artisan nova:tool acme/price-tracker`
Python3 is installed by default in Ubuntu 20.04 (used by the Dockerfiles), but Python2 was required during the installation step of creating the Nova tool, as was libpng-dev, so these have been added to the Dockerfiles.
You might not want to accept this PR as it's very specific to Nova, but if not then maybe this info will help someone else who gets stuck like I did.
- Install fresh Laravel project with Sail and Nova
- Try to create a new Nova tool as above, which will result in an error without this PR
**Python2 dependency error:**
**Libpng-dev dependency error:**
> [1.x] Added python2 and libpng-dev to both runtime Dockerfile contents

- bin/sail
I'm not sure this is exactly necessary, but I think it would be a nice addition, and would allow a better integration between sail and node. I'm currently doing `sail shell` and running npx from within the container, which doesn't feel as streamlined.
Just a thought.
> Allow sail to run npx directly

- bin/sail
Fix: sail mysql doesn't pass variables correctly to the bash
Fix: sail mysql always using root to connect even if mysql_user in .env isn't root
> Fix mysql proxy variables

- runtimes/7.4/Dockerfile
- runtimes/8.0/Dockerfile
- sail.sh
Many users prefer Yarn over NPM, this PR adds support for it to Sail.
Yarn is added via apt and the sail.sh script has been modified to forward yarn commands to the container.
> Yarn support

- stubs/docker-compose.yml
Avoid circular reference in between selenium and laravel.test
The error that is thrown when uncommenting all the lines is :
`ERROR: Circular dependency between laravel.test and selenium and redis`
> [1.x] Fix for circular dependency error with selenium

- bin/sail
Adding sail bash to Initiate a bash shell within the application container like sail shell.
I caught myself typing sail bash more than one time instead of sail shell
> add sail bash to Initiate a Bash shell within the application container

- bin/sail
All error messages are sent to STDERR when the sail binary fails to start
> [1.x] Send error messages to STDERR

- bin/sail
Without looking into the base container image there is no documented way to know what is the root password and there is no sudo, so I've added a `root-shell` to `bin/sail`.
Other relevant options which solve the same issue: add `sudo` and add `sail` user to sudoers or document root password.
> [1.x] root-shell added to bin/sail

- stubs/docker-compose.yml
Adding these healthchecks allows a user to check the availability and status of a container and allows docker-compose services to wait on services they depend on to be healthy before starting themselves.
> [1.x] Add healthcheck for mysql and redis service in docker-compose

- stubs/docker-compose.yml
Adding these healthchecks allows a user to check the availability and status of a container and allows docker-compose services to wait on services they depend on to be healthy before starting themselves.
> [1.x] Append PostgreSQL HealthCheck

- bin/sail
This adds support for running `sail dusk:fails` as running `sail artisan dusk:fails` doesn't work properly.
If this is merged, I will add a PR adding usage instructions on the Laravel docs repository.
> Add support for dusk:fails

- bin/sail
This is a small yet separate addendum to my other PR: https://github.com/laravel/sail/pull/44
This PR changes the provided password for to the MySQL CLI on the `sail mysql` command from `MYSQL_ROOT_PASSWORD` to `MYSQL_PASSWORD`.
Context:
This is for custom Docker Compose setups from before Laravel Sail came out. Sail automatically sets the `MYSQL_ROOT_PASSWORD` env variable to `.env`'s DB_PASSWORD.
When working with a Docker Compose configuration that have separate passwords between the MySQL root user and the MySQL working (i.e. non-root) user, `sail mysql` will throw the classic 'Access denied for user X (using password: YES)' MySQL error.
One could also argue that the current call to the MySQL CLI is erroneous since it combines MYSQL_USER (not root) and MYSQL_ROOT_PASSWORD.
This PR …
> Use non-root MySQL password for `sail mysql`

- bin/sail
Spent many hours scratching my head not realizing that a service I knew wasn't working yet was causing me to not be able to run sail art migrate which was needed by the failed service
This will now print out a message with the failed services and that it is shutting down
```
[philip@philip-xps laravel]$ sail shell
laravel_monitoring_1     laravel-monitoring               Exit 1                                          
Shutting down sail
Sail is not running.
You may Sail using the following commands: './vendor/bin/sail up' or './vendor/bin/sail up -d'
[philip@philip-xps laravel]$ 
```
> Inform user when running docker-compose down

- runtimes/7.4/start-container
- runtimes/7.4/supervisord.conf
- runtimes/8.0/start-container
- runtimes/8.0/supervisord.conf
On start, supervisor throws up a couple warnings about implied configurations. The warnings are minor but since the corrections are simple it seems worthwhile. 
No changes are made to the actual functionality here.
> Cleanup supervisord warnings on start

- runtimes/7.4/supervisord.conf
- runtimes/8.0/supervisord.conf
The default value for `logfile` is `$CWD/supervisord.log` and for `pidfile` is `$CWD/supervisord.pid` [(supervisord section settings).](http://supervisord.org/configuration.html#supervisord-section-settings)
Those settings omitted in the current configuration. So supervisor creates `supervisord.log` and `supervisord.pid` in current working directory `/var/www/html`. That directory has been mounted to the user's filesystem, let's use the proper location.
> [1.x] Change supervisord logfile and pidfile settings

- runtimes/7.4/Dockerfile
- runtimes/8.0/Dockerfile
Because Laravel's new `schema:dump` functionality uses `pg_restore` to migrate, it needs to be available in the app container. Currently a project using schema dumps cannot migrate if it uses Sail.
> Add missing PostgreSQL clients

- src/Console/PublishCommand.php
Currently, the publish command does not replace the PHP 7.4 runtime correctly, this fixes that.
> Update the publish command to consider PHP 7.4

- src/Console/InstallCommand.php
Needs a co-PR to the Sail container to add a sail user on "sail up".
Fixes https://github.com/laravel/sail/issues/70
> [1.x] Use different DB user for Sail

- src/Console/InstallCommand.php
This update fixes an issue that is caused if you already have a DB_PASSWORD configured in your .env. Prior to this change, if you have this (for example):
```
DB_PASSWORD=mypassword
```
After running `sail:install` it would then look like this:
```
DB_PASSWORD=passwordmypassword
```
And each time you run `sail install` it'll keep growing. This is because only DB_PASSWORD= is being replaced, when it should be replacing the password as well, which can be accomplished using `preg_replace` and a simple regex as in this PR.
> [1.x] Patch issue with environment database password replacement

- runtimes/8.0/Dockerfile
Running `./vendor/bin/sail build` will throw an error when trying to install Swoole via PECL.
```
> [5/12] RUN pecl install swoole:
No releases available for package "pecl.php.net/swoole"
install failed
```
Reason for this is that the package index is missing and must first be updated.
This PR resolves the issue by extending the Dockerfile for PHP 8.0 to run `pecl channel-update` before trying to install Swoole.
> Load missing PECL package index before installing Swoole.

- bin/sail
Add option to Access the mysql shell when running mariadb in place of mysql service.
Running `sail mysql` is a very helpful tool to access mysql shell. 
With the addition of support for mariadb in #119 it would be really awesome to accord mariadb users to a similar experience.
This PR adds support to run: `sail mariadb` and access the good old MySQL shell.
Running `sail mysql` when running mariadb fails with the error `ERROR: No such service: mysql`
> Add MySQL shell when running mariadb

- src/Console/InstallCommand.php
- stubs/minio.stub
This PR add support for [MinIO](https://min.io/) ([GitHub](https://github.com/minio/minio/blob/master/docs/docker/README.md)) to Sail during the install process. It includes a `minio.stub` file to be included in the final `docker-compse.yml` file and updates to the `InstallCommand`.
MinIO is an S3 compatible object storage service and is a great compliment to the Laravel development experience so you don't have to use dev S3 buckets.
> Add MinIO to sail:install Command

- runtimes/8.0/Dockerfile
`pecl install swoole` writes a number of files into /tmp when compiling the extension. 
This PR runs some cleanup commands to reduce the data stored in that docker image layer
> Clear pecl caches & tmp files during swoole extension install

- .github/ISSUE_TEMPLATE/1_Bug_report.md
This will help us determine which OS they're attempting to run Sail on. I've also removed the Database Driver since that isn't really relevant for Sail bug reports.
> [1.x] Ask for OS in bug report

- stubs/mariadb.stub
- stubs/minio.stub
- stubs/mysql.stub
- stubs/pgsql.stub
- stubs/redis.stub
This small patch will help with the support of podman, as some options are required unlike with docker-compose.
should not have any side effects, and even can help if for some reason the service is not ready.
```
ERROR: for redis  Cannot create container for service redis: fill out specgen: healthcheck-retries must be greater than 0
ERROR: Encountered errors while bringing up the project.
```
> Add retries & timeout to healthcheck

- src/Console/InstallCommand.php
If you are using MeiliSearch for Scout or MinIO for Storage, you must be make sure they are running, even if they are optional, just like Redis.
> [1.x] Append MeiliSearch and MinIO to depends

- stubs/meilisearch.stub
Adding these healthchecks allows a user to check the availability and status of a container and allows docker-compose services to wait on services they depend on to be healthy before starting themselves.
> [1.x] Append MeiliSearch HealthCheck

- runtimes/7.4/Dockerfile
- runtimes/8.0/Dockerfile
Hi,
Lets use node 16.x, since Node.js v15 is EOL now.
FYI: Node 16 comes with npm v7.x
I would suggest not to use `odd` (11,13,15,17, etc) version number. They are not being supported for long time.
Thanks
> Use node.js v16.x

- bin/sail
Including a proxy for the binaries in the vendor folder, in addition to decreasing the steps for its execution (which today needs to be done via `sail shell` and then `vendor/bin/binary`), also allows other scripts to run these binaries from simplest way. An example would be the use of *php-cs-fixer*, *phpmd* or other static parser, not only via terminal (executed by the user) but also via a hook for commits or push.
Running a vendor binary today:
```shell
sail shell
vendor/bin/php-cs-fixer ...
```
Running a vendor binary with the proxy:
```shell
sail bin php-cs-fixer ...
```
According to [Docker docs](https://docs.docker.com/compose/reference/), the "bin" word is not used for any specific command in the docker-compose cli, so this addition will not break the existing structure
> [1.x] Add proxy to vendor binaries

- bin/sail
This is a small change that should help people who like to run e2e tests in containers defined in there docker-compose or any other short lived container.
This patch changes the behavior of Laravel sail to only shutdown the containers if and only if the main PHP containers goes down.
before this patch if any service defined `docker-compose.yaml`  would shutdown for any reason. so would all other containers upon excuting any `sail` command
Which meant that if you would try to Debug or restart that one service.
for example if you would like to inspect the logs of that container with for example  `sail logs <servicename>` 
it would shutdown all containers because it found a stopped container.
This patch should change this behavior to only stop the stack if the main service goes down
> [1.x] Update Sail script to only exit if Main Exits

- runtimes/7.4/Dockerfile
- runtimes/8.0/Dockerfile
This updates the default Ubuntu version to 21.04 which hopefully will solve the current libssl issues people are experiencing.
> [1.x] Update to Ubuntu 21.04

- runtimes/7.4/Dockerfile
This ensures the codename in the PPA matches the current distribution.
Making any changes to the Ubuntu version will reflect in the PPA.
FROM ubuntu:21.04 -> hirsute
FROM ubuntu:20.04 -> focal
```
grep UBUNTU_CODENAME /etc/os-release | cut -d= -f2
```
> retrieve php packages from current ubuntu codename

- runtimes/8.0/Dockerfile
laravel/sail#171 for PHP 8.0
> This ensures the codename in the PPA matches the current distribution.
> 
> Making any changes to the Ubuntu version will reflect in the PPA.
> 
> FROM ubuntu:21.04 -> hirsute
> FROM ubuntu:20.04 -> focal
> [1.x] Retrieve php packages from current ubuntu codename for PHP 8.0

- runtimes/7.4/Dockerfile
- runtimes/8.0/Dockerfile
- Revert "[1.x] Retrieve php packages from current ubuntu codename for PHP 8.0"
- Revert "retrieve php packages from current ubuntu codename (#171)"
- Revert "Update to Ubuntu 21.04 (#169)"
> revert ubuntu 21.04

- bin/sail
Please check comments from laravel/sail#170. 
I'm research **expose** code and found what without empty `--subdomain` option **expose** use `http` from `http://host.docker.internal:80` (`{host}` argument) as subdomain.
This change set empty subdomain as default, but if you use this option in `sail share` command it rewrite default value.
```shell
sail share                      # expose generate random subdomain
sail share --subdomain=test     # use test as subdomain
```
<hr>
**P.S.** The `-t` flag for `docker run` allows you to output the remaining time on one line, rather than every second on a separate line.
> [1.x] Append random subdomain by default.

- bin/sail
`SEDCMD` isn't used anywhere in the script so this block of code isn't needed.
> Remove Unused SEDCMD

- runtimes/8.0/Dockerfile
This adds PCOV code coverage tool to 8.0 runtime.
I know this is customizable, but since 7.4 runtime has it enabled, it would be nice to have it enabled on the 8.0 as well.
> [1.x] Add pcov to php 8.0 runtime

- README.md
The logo isn't displayed in `Packagist` because of the relative file path. This fix makes the full path to `HEAD`.
> [1.x] Fix logo for Packagist.

- stubs/minio.stub
Added Added Minio console port. Default set to 8900 but subject to approval by the community. 
---
Fixes an issue where Minio show the following error in the logs and on opening localhost:9000 redirects to a random port.
```
WARNING: Console endpoint is listening on a dynamic port (41045), please use --console-address ":PORT" to choose a static port.
```
This PR allows one to access Minio dashboard on port 8900 and the API endpoint remains on port 9000. 
Example repo: https://github.com/SamuelMwangiW/sail-minio-example/
> Minio Console Port

- bin/sail
This line is missing a backslash, causing commands not to be passed. So using `--subdomain` has no effect, and it always use the randomized one.
> Fixes missing backslash

- bin/sail
- src/SailServiceProvider.php
This PR will allow developers to modify or add commands to the sail script.
If you decided to add a new custom service to the docker-compose.yml file and expose a command for this service via sail, you may add the command to the published sail script at the root of your app. For example, if you added a mongo service to your app you can make the mongo shell available by adding:
```bash
.
.
elif [ "$1" == "mongo" ]; then
if [ "$EXEC" == "yes" ]; then
docker-compose exec mongo mongo
else
sail_is_not_running
fi
elif
.
.
```
Currently, the script will be published by executing `sail artisan sail:publish` command, I was wondering if it should be published via its own command like `sail artisan sail:publish-script` so that developers can publish it on demand.
Also, The user doesn't have to …
> make sail script publishable

- src/Console/PublishCommand.php
In #201 to tag `sail` added bash script and added separate tag `sail-docker` to publish only docker directory
> [1.x] Publish only docker directory

- src/Console/InstallCommand.php
- stubs/devcontainer.stub
I'm working with the VS Code & GitHub teams and we like to propose the following idea.
When working in projects that have a complex infrastructure - say a MySQL backend, with Redis for caching - it's hard to get the project started due to infrastructure setup. Thanks to Sail, Laravel addresses most of those problems, making it easy to start new projects. We want to improve that experience even further by enabling the current project setup to “just work” in VS Code.
Imagine opening a folder with a Laravel project and the editor takes care of setting up the environment automatically for the user. Not only on the infrastructure level, but also installing the required editor extensions so the developer can start hacking right away.
By adding a `.devcontainer/devcontainer.json` file to a …
> adds devcontainer to install command

- bin/sail
Call `source .env` before exporting bash environment variables ( I guess they are default values for sail )
closes https://github.com/laravel/sail/issues/206
> Call `source .env` before exporting bash environment variables ( I guess they are default values for sail )

- bin/sail
Add `"$@"` to pass additional command-line arguments for `shell` / `root-shell` to `bash` in container.
This allows things like `sail shell -c "cd some-sub-module && npm install"`
> Pass additional arguments to shell / root-shell commands

- bin/sail
- runtimes/7.4/Dockerfile
- runtimes/8.0/Dockerfile
- stubs/docker-compose.stub
I'm aware that this has been attempted in previous PRs that have been denied but I thought I'd take another chance as I believe my implementation has a rather small footprint and may be more palatable to the maintainers of this repository. 
I do understand their desire to keep this project lean but I have a hard time understanding how a step debugger isn't included in any basic local development environment.
This installs Xdebug 3.0 using the php7.4 and php8.0 packages and relies on the two built in env vars already provided by xdebug: `XDEBUG_MODE` and `XDEBUG_CONFIG` to control and configure the extension. These are mapped directly to `SAIL_XDEBUG_MODE` and `SAIL_XDEBUG_CONFIG` that can be controlled in the projects .env file.
[XDEBUG_MODE](https://xdebug.org/docs/step_debug#mode) is …
> Added xdebug 3.0 to the project using xdebugs built-in env vars.

- bin/sail
The `sail dusk` and `sail dusk:fails` currently have the `APP_URL` value hard coded to http://laravel.test, this replaces the hard code with a reference to `$APP_SERVICE`.
Issue reported here: https://github.com/laravel/sail/issues/212
> [1.x] Removes hardcoded service name from APP_URL in dusk and dusk:fails command

- stubs/docker-compose.stub
Fantastic implementation of xdebug 3.0 by `Nick Haynes` in PR [#209], I think it's very pertinent to have the option of a step debugger built into the container.
However, in the PR description, which has even been approved and merged, `Nick Haynes` cites the issue that `host.docker.internal` is not available in containers running in linux environments, and the fact that users of this OS have to update the environment variable in their projects using the command below:
```
docker inspect -f {{range.NetworkSettings.Networks}}{{.Gateway}}{{end}} <container-name>
```
However, I would like to make a small contribution, which I believe is valid, as it will bring greater compatibility between Windows, Mac and Linux environments, so that we do not need extra commands to detect the IP of the …
> Adding extra_hosts to the compose file stubs for automatic host.docker.internal mapping

- bin/sail
When setting the SKIP_SAIL_CHECKS env variable the docker exec will speed up a bit
> Allow skip of sail checks

- stubs/docker-compose.stub
Currently, the default value of XDEBUG_MODE is set to the unquoted value `off`. This causes the docker yaml parser to parse the value `off` as the boolean `false`. Due to this xdebug will display an error each time that it's initialized, see the image below:
In order to fix this, the value `off` should be enclosed by strings as mentioned in [the docker-compose v3 spec](https://docs.docker.com/compose/compose-file/compose-file-v3/): "YAML boolean values ("true", "false", "yes", "no", "on", "off") must be enclosed in quotes, so that the parser interprets them as strings."
> Enclose default XDEBUG_MODE in quotes

- stubs/docker-compose.stub
This PR reverts https://github.com/laravel/sail/pull/231 because the quotes around the default value are making Xdebug complain about an invalid value:
With `XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-"off"}'` the quotes are being included in the string itself:
With `XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'` it doesn't trigger the error and passes the right `off` (unquoted) string to Xdebug:
This kind of make sense given that the string interpolation already happens inside single quotes? `XDEBUG_MODE: '${...}'`
Not sure if this behavior is different across docker versions so I'll include mine:
OS: MacOS 11.4
Docker version: 20.10.7, build f0df350
Sail version: v1.10.1
> Revert quoted XDEBUG_MODE environment variable

- bin/sail
In the context of deploying my code, I would like to use Sail to run various tests etc. Currently, however, this fails in places due to the execution of commands and the error message `the input device is not a TTY`. By adding the parameter `-T` to the execution of docker-compose via `export SAIL_SET_TTY=y`, this error no longer occurs.
> Implementation of an option to disable the pseudo-tty allocation

- bin/sail
Sometime you need always use one domain in project tests.
.env | option | result subdomain
--- | --- | ---
None | None | Random
None | from-option | from-option
from-env | None | from-env
from-env | from-option | from-option
rel. #170
> [1.x] Environment variable for share subdomain.

- bin/sail
Reverts laravel/sail#236
Because flag `-T` in `docker-compose exec` disable TTY and broken commands like `sail php`, `sail tinker`, `sail node` etc. which are waiting for user input. They wait infinit. And disable colorize in other commands.
It is necessary to understand the problem in detail and a more precise solution for laravel/sail#236.
> Revert "Implementation of an option to disable the pseudo-tty allocation"

- bin/sail
Since the `compose` docker cli plugin is now released I was not able to use the sail cli any longer.
This pull request conditionally tries to alias the docker-compose command with the usage of the respective cli plugin and lets docker continue to be responsible for reporting whether it is installed or not.
> alias the usage of docker-compose with the compose cli plugin if docker-compose can not be executed

- stubs/mysql.stub
This updates the MySQL stub to use the official `mysql/mysql-server` image which has an ARM build that works on Apple Silicon without needing a `platform` directive in your `docker-compose.yml` file.
> Update stub for arm image

- runtimes/7.4/start-container
- runtimes/8.0/start-container
- runtimes/8.1/start-container
Just giving this keywords some room to breathe as the ones above them to keep the whole file consistent.
> [1.x] Add missing spaces before `then` keywords

- runtimes/7.4/Dockerfile
- runtimes/8.0/Dockerfile
- runtimes/8.1/Dockerfile
If `NODE_VERSION` declared as `ENV` variable and overwritten in `docker-compose.yml`, new value is not available in build.
It's must be declared as `ARG` and overwritten in `build.args` section on the service.
Ref: laravel/sail#261
> [1.x] Fix NODE_VERSION on build.

- runtimes/8.1/Dockerfile
It seems like the previously disabled PHP 8.1 extensions (see f3b2993) msgpack,  igbinary, redis, swoole, memcached, pcov and xdebug are now available - the image build now succeeds.
> Re-enable previously disabled PHP 8.1 extensions

- stubs/meilisearch.stub
MeiliSearch v0.24 had a breaking change and moved the database folder 
from `/data.ms` to `/home/meili/data.ms`, so to keep using `/data.ms`, we 
need to set the `MEILI_DB_PATH` environment variable. This also avoids
trouble in the future when the data might move again, inside `/var`.
Refs:
- Release notes: https://github.com/meilisearch/MeiliSearch/releases/tag/v0.24.0
- Issue: https://github.com/meilisearch/MeiliSearch/issues/1969
> Set meilisearch data path

- stubs/meilisearch.stub
Reverts laravel/sail#299
Reverting this because it causes Sail to throw permissions errors: https://github.com/laravel/sail/issues/300
> [1.x] Revert "Set meilisearch data path"

- src/Console/InstallCommand.php
- stubs/mariadb.stub
- stubs/meilisearch.stub
- stubs/minio.stub
- stubs/mysql.stub
- stubs/pgsql.stub
- stubs/redis.stub
To normalize the names of volumes a bit, I've added separators between the two words `sail` and `service-name`.
I've also added the `MYSQL_ROOT_HOST` variable to the `mariadb` container, documented here: https://hub.docker.com/_/mariadb/
> Add separator between volume names

- stubs/meilisearch.stub
Hi. It works fine. `platform` can be removed.
ref. https://github.com/meilisearch/MeiliSearch/pull/1897
> meilisearch is now also available for arm64

- runtimes/8.0/Dockerfile
Fixes https://github.com/laravel/sail/issues/314
As described in https://github.com/laravel/sail/issues/314, the php8.0 runtime installs packages which recommend php-pear which depends on the most recent version of php (8.1).  The results in php8.1 getting installed as the default runtime.  The PR suggest adding –no-install-recommends to the apt-get command in the Dockerfile to prevent the recommendations from being installed.  
I tried this change out and it did prevent php8.1 from being installed.  However, it does mean that php-pear (and any other recommends) are not installed.  As far as I am aware, sail does not depend on php-pear and the container seems to run fine without it (default Laravel page opens in the browser). 
We could also fix this by running an apt-get remove php8.1-cli …
> Fix php8.0-dev depending on php8.1-cli
